import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/Header.jsx'
import Section1 from '../components/Sections/Section1.jsx'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://kit.fontawesome.com/a076d05399.js"></script>
        <link rel="stylesheet" href="file:///E:/fontawesome/css/all.css" />
        <script src="file:///E:/jquery.js"></script>
      </Head>

      <Header />
      <Section1 />


    </div>
  )
}
