import Head from 'next/head'
import Header from '../components/Header.jsx'
import Footer from '../components/Footer'
import BtnSlider from '../components/Slideshow/BtnSlider.jsx'
import Slider from '../components/Slideshow/Slider.jsx'


export default function Home() {
  return (
    <div >

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"></link>
      </Head>

      <Header />
      <Slider />
      <Footer />

    </div>
  )
}
